# Generated by Django 3.2.5 on 2021-07-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='Menu',
        ),
    ]
