# Generated by Django 3.2.5 on 2021-07-21 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_rename_states_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('ordered', 'ordered'), ('confirmed', 'confirmed'), ('delivering', 'delivering'), ('delivered', 'delivered')], default=1, max_length=100, null=True)),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu_items', models.ManyToManyField(to='dashboard.Menu')),
            ],
        ),
    ]
