# Generated by Django 3.2.5 on 2021-07-21 12:57

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20210721_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('webesite', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Company',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menu_category',
            options={'verbose_name_plural': 'Menu Category'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('unit_type', models.CharField(blank=True, choices=[('Piece', 'Piece'), ('KG', 'KG'), ('Liter', 'Liter'), ('Gallon', ' Gallon'), ('Package', 'Package')], default='Piece', max_length=150, null=True)),
                ('Unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('totol_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=dashboard.models.stock_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
