# Generated by Django 3.2.5 on 2021-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='next',
            field=models.BooleanField(default=False),
        ),
    ]
