# Generated by Django 3.2.5 on 2021-07-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_menu_next'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='next',
            new_name='new',
        ),
    ]
