# Generated by Django 3.2.5 on 2021-07-23 11:14

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='tell me about yourself')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='what is your phone?')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='where do you live?')),
                ('photo', models.ImageField(blank=True, default='default.png', null=True, upload_to=dashboard.models.profile_location, verbose_name='Upload a square picture of yourself.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
