# Generated by Django 3.2.5 on 2021-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, default='default-pizza.png', null=True, upload_to='menu'),
        ),
    ]
