# Generated by Django 3.2.5 on 2021-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_menu_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('min_order', models.SmallIntegerField(blank=True, null=True)),
                ('geojson', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Area',
            },
        ),
    ]
