# Generated by Django 3.2.5 on 2021-08-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210814_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('confirmed', 'confirmed'), ('delivering', 'delivering'), ('delivered', 'delivered')], default=1, max_length=100, null=True),
        ),
    ]
