# Generated by Django 3.2.5 on 2021-08-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('confirmed', 'confirmed'), ('delivering', 'delivering'), ('delivered', 'delivered')], default=1, max_length=100),
        ),
    ]
