# Generated by Django 3.2.5 on 2021-08-29 19:59

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, default='default.png', null=True, upload_to=dashboard.models.customer_profile_location, verbose_name='Upload a square picture of yourself.')),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
