# Generated by Django 3.2.5 on 2021-09-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
    ]
