# Generated by Django 3.2.5 on 2021-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_order_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
