# Generated by Django 3.2.5 on 2021-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_order_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu_category',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
