# Generated by Django 3.2.5 on 2021-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20211005_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
