# Generated by Django 3.2.5 on 2021-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pay_ref',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
