# Generated by Django 3.2.5 on 2021-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_order_order_pay_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
