# Generated by Django 3.2.5 on 2021-11-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_order_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu')),
            ],
        ),
    ]
