# Generated by Django 3.2.5 on 2021-11-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_menu_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ingrediant',
            },
        ),
        migrations.RemoveField(
            model_name='menu_tags',
            name='name',
        ),
        migrations.AlterField(
            model_name='menu_tags',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu'),
        ),
        migrations.AddField(
            model_name='menu_tags',
            name='ingrediant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ingrediants'),
        ),
    ]
