# Generated by Django 3.2.5 on 2021-11-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20211110_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_tags',
            name='ingrediant',
        ),
        migrations.AddField(
            model_name='menu_tags',
            name='ingrediant',
            field=models.ManyToManyField(to='dashboard.Ingrediants'),
        ),
        migrations.AlterField(
            model_name='menu_tags',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu'),
        ),
    ]
