# Generated by Django 3.2.5 on 2021-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20211110_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_tags',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu_tags',
            name='menu',
            field=models.ManyToManyField(to='dashboard.Menu'),
        ),
    ]
