# Generated by Django 3.2.5 on 2022-01-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20211110_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_list', to='dashboard.order'),
        ),
    ]
